# User config
author: "Christopher-LeeNU"
tagline: "Chris Lee's portfolio"
description: "I'm a robotics student at Northwestern University. Here are my projects!"
keywords: "Chris, Lee, Robotics"
email: "christopherlee91.22@gmail.com"
linkedin: "https://www.linkedin.com/in/christopher-l-b24a83164"
github: "https://github.com/Christopher-LeeNU"

# Site config
baseurl: "/pineapple"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
